In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Smart_Eco_Sales_Dataset.csv')
print(df)
df = pd.DataFrame(df)
df

    OrderID   OrderDate     Product        City  Quantity  UnitPrice  Revenue  \
0   ORD0001  2026-06-13   EcoBottle        Pune         9       2506    22554
1   ORD0002  2026-05-20   EcoBottle     Solapur         2        744     1488
2   ORD0003  2026-05-24   SolarLamp     Solapur         8       4179    33432
3   ORD0004  2026-03-29   SmartPlug      Nashik         7       3257    22799
4   ORD0005  2026-03-30  WaterMeter  Aurangabad         2       4263     8526
..      ...         ...         ...         ...       ...        ...      ...
95  ORD0096  2026-01-11   AirSensor    Kolhapur        20       2551    51020
96  ORD0097  2026-01-06  HealthBand  Aurangabad        19        829    15751
97  ORD0098  2026-04-24   SmartPlug      Nashik        19       4070    77330
98  ORD0099  2026-04-15   SmartPlug    Kolhapur         4       1817     7268
99  ORD0100  2026-04-13  WaterMeter        Pune        15       1221    18315

    CustomerRating SalesChannel Returned  EstimatedCO2SavedKg
0              3.4  Distributor      Yes                15.81
1              3.2       Online       No                 3.17
2              4.2       Online       No                14.45
3              3.2       Retail      Yes                 7.18
4              4.1       Retail      Yes                 2.94
..             ...          ...      ...                  ...
95             3.1       Online       No                31.01
96             4.5       Online       No                26.48
97             4.3       Retail      Yes                24.34
98             3.7  Distributor       No                 3.45
99             3.6       Retail      Yes                36.47

[100 rows x 11 columns]

,OrderID,OrderDate,Product,City,Quantity,UnitPrice,Revenue,CustomerRating,SalesChannel,Returned,EstimatedCO2SavedKg
0,ORD0001,2026-06-13,EcoBottle,Pune,9,2506,22554,3.4,Distributor,Yes,15.81
1,ORD0002,2026-05-20,EcoBottle,Solapur,2,744,1488,3.2,Online,No,3.17
2,ORD0003,2026-05-24,SolarLamp,Solapur,8,4179,33432,4.2,Online,No,14.45
3,ORD0004,2026-03-29,SmartPlug,Nashik,7,3257,22799,3.2,Retail,Yes,7.18
4,ORD0005,2026-03-30,WaterMeter,Aurangabad,2,4263,8526,4.1,Retail,Yes,2.94
...,...,...,...,...,...,...,...,...,...,...,...
95,ORD0096,2026-01-11,AirSensor,Kolhapur,20,2551,51020,3.1,Online,No,31.01
96,ORD0097,2026-01-06,HealthBand,Aurangabad,19,829,15751,4.5,Online,No,26.48
97,ORD0098,2026-04-24,SmartPlug,Nashik,19,4070,77330,4.3,Retail,Yes,24.34
98,ORD0099,2026-04-15,SmartPlug,Kolhapur,4,1817,7268,3.7,Distributor,No,3.45
99,ORD0100,2026-04-13,WaterMeter,Pune,15,1221,18315,3.6,Retail,Yes,36.47

In [4]:
print("First 3 rows:")
display(df.head(3))

print("\nLast 3 rows:")
display(df.tail(3))

First 3 rows:

,OrderID,OrderDate,Product,City,Quantity,UnitPrice,Revenue,CustomerRating,SalesChannel,Returned,EstimatedCO2SavedKg
0,ORD0001,2026-06-13,EcoBottle,Pune,9,2506,22554,3.4,Distributor,Yes,15.81
1,ORD0002,2026-05-20,EcoBottle,Solapur,2,744,1488,3.2,Online,No,3.17
2,ORD0003,2026-05-24,SolarLamp,Solapur,8,4179,33432,4.2,Online,No,14.45

Last 3 rows:

,OrderID,OrderDate,Product,City,Quantity,UnitPrice,Revenue,CustomerRating,SalesChannel,Returned,EstimatedCO2SavedKg
97,ORD0098,2026-04-24,SmartPlug,Nashik,19,4070,77330,4.3,Retail,Yes,24.34
98,ORD0099,2026-04-15,SmartPlug,Kolhapur,4,1817,7268,3.7,Distributor,No,3.45
99,ORD0100,2026-04-13,WaterMeter,Pune,15,1221,18315,3.6,Retail,Yes,36.47

In [5]:

print("\nInfo:")
df.info()

print("\nDescribe:")
display(df.describe())

print("\nShape (rows, columns):", df.shape)

Info:
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OrderID              100 non-null    str
 1   OrderDate            100 non-null    str
 2   Product              100 non-null    str
 3   City                 100 non-null    str
 4   Quantity             100 non-null    int64
 5   UnitPrice            100 non-null    int64
 6   Revenue              100 non-null    int64
 7   CustomerRating       100 non-null    float64
 8   SalesChannel         100 non-null    str
 9   Returned             100 non-null    str
 10  EstimatedCO2SavedKg  100 non-null    float64
dtypes: float64(2), int64(3), str(6)
memory usage: 8.7 KB

Describe:

,Quantity,UnitPrice,Revenue,CustomerRating,EstimatedCO2SavedKg
count,100.000000,100.000000,100.000000,100.00000,100.000000
mean,11.160000,2704.270000,30996.150000,4.05800,14.896100
std,5.970838,1305.960816,23661.931993,0.56536,11.547851
min,1.000000,620.000000,1416.000000,3.10000,0.330000
25%,6.000000,1434.000000,9852.000000,3.60000,6.017500
50%,11.500000,2770.000000,25069.500000,4.10000,12.065000
75%,17.000000,3979.000000,46547.000000,4.50000,21.055000
max,20.000000,4909.000000,98160.000000,5.00000,48.910000

Shape (rows, columns): (100, 11)

In [6]:
print("loc example (rows 0-2, specific columns):")
display(df.loc[0:2, ["Quantity", "UnitPrice", "Revenue"]])

print("\niloc example (first 3 rows, first 3 columns):")
display(df.iloc[0:3, 0:3])


print("\nBoolean indexing (City == 'Pune'):")
display(df[df["City"] == "Pune"])

loc example (rows 0-2, specific columns):

   Quantity  UnitPrice  Revenue
0         9       2506    22554
1         2        744     1488
2         8       4179    33432

iloc example (first 3 rows, first 3 columns):

   OrderID   OrderDate    Product
0  ORD0001  2026-06-13  EcoBottle
1  ORD0002  2026-05-20  EcoBottle
2  ORD0003  2026-05-24  SolarLamp

Boolean indexing (City == 'Pune'):

,OrderID,OrderDate,Product,City,Quantity,UnitPrice,Revenue,CustomerRating,SalesChannel,Returned,EstimatedCO2SavedKg
0,ORD0001,2026-06-13,EcoBottle,Pune,9,2506,22554,3.4,Distributor,Yes,15.81
14,ORD0015,2026-02-10,AirSensor,Pune,9,4600,41400,4.5,Distributor,Yes,19.82
24,ORD0025,2026-06-15,EcoBottle,Pune,13,3279,42627,4.6,Online,No,8.33
26,ORD0027,2026-05-21,EcoBottle,Pune,18,620,11160,4.9,Online,No,20.43
29,ORD0030,2026-05-29,HealthBand,Pune,11,968,10648,3.1,Retail,No,25.46
30,ORD0031,2026-05-16,SolarLamp,Pune,17,1156,19652,4.7,Online,No,6.06
36,ORD0037,2026-06-17,WaterMeter,Pune,18,2952,53136,4.9,Online,No,14.55
43,ORD0044,2026-02-15,AirSensor,Pune,6,3221,19326,4.6,Retail,No,4.88
45,ORD0046,2026-02-28,SolarLamp,Pune,7,3764,26348,3.7,Online,No,7.05
52,ORD0053,2026-04-14,WaterMeter,Pune,10,2850,28500,3.4,Distributor,No,17.06
66,ORD0067,2026-04-30,SolarLamp,Pune,13,722,9386,3.2,Retail,No,28.52
85,ORD0086,2026-05-06,EcoBottle,Pune,19,2829,53751,3.9,Retail,No,11.86
89,ORD0090,2026-04-20,SmartPlug,Pune,20,1312,26240,4.9,Online,No,16.17
91,ORD0092,2026-05-01,SmartPlug,Pune,8,2860,22880,4.4,Distributor,No,2.91
93,ORD0094,2026-02-06,EcoBottle,Pune,6,3019,18114,4.2,Distributor,No,7.26
99,ORD0100,2026-04-13,WaterMeter,Pune,15,1221,18315,3.6,Retail,Yes,36.47

In [7]:
print("Type",type(df))
print("columns",list(df.columns))
print("Index:", df.index.tolist())

Type <class 'pandas.DataFrame'>
columns ['OrderID', 'OrderDate', 'Product', 'City', 'Quantity', 'UnitPrice', 'Revenue', 'CustomerRating', 'SalesChannel', 'Returned', 'EstimatedCO2SavedKg']
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

In [8]:
print("Missing values per column:")
display(df.isnull().sum())

print("\nRows with any missing values:")
display(df[df.isnull().any(axis=1)])

print("\nDropping rows with missing values (dropna):")
display(df.dropna())

print("\nFilling missing Quantity with the column mean (fillna):")
df_filled = df.copy()
df_filled["Quantity"] = df_filled["Quantity"].fillna(df_filled["Quantity"].mean())
display(df_filled)

Missing values per column:

OrderID                0
OrderDate              0
Product                0
City                   0
Quantity               0
UnitPrice              0
Revenue                0
CustomerRating         0
SalesChannel           0
Returned               0
EstimatedCO2SavedKg    0
dtype: int64

Rows with any missing values:

Empty DataFrame
Columns: [OrderID, OrderDate, Product, City, Quantity, UnitPrice, Revenue, CustomerRating, SalesChannel, Returned, EstimatedCO2SavedKg]
Index: []

Dropping rows with missing values (dropna):

,OrderID,OrderDate,Product,City,Quantity,UnitPrice,Revenue,CustomerRating,SalesChannel,Returned,EstimatedCO2SavedKg
0,ORD0001,2026-06-13,EcoBottle,Pune,9,2506,22554,3.4,Distributor,Yes,15.81
1,ORD0002,2026-05-20,EcoBottle,Solapur,2,744,1488,3.2,Online,No,3.17
2,ORD0003,2026-05-24,SolarLamp,Solapur,8,4179,33432,4.2,Online,No,14.45
3,ORD0004,2026-03-29,SmartPlug,Nashik,7,3257,22799,3.2,Retail,Yes,7.18
4,ORD0005,2026-03-30,WaterMeter,Aurangabad,2,4263,8526,4.1,Retail,Yes,2.94
...,...,...,...,...,...,...,...,...,...,...,...
95,ORD0096,2026-01-11,AirSensor,Kolhapur,20,2551,51020,3.1,Online,No,31.01
96,ORD0097,2026-01-06,HealthBand,Aurangabad,19,829,15751,4.5,Online,No,26.48
97,ORD0098,2026-04-24,SmartPlug,Nashik,19,4070,77330,4.3,Retail,Yes,24.34
98,ORD0099,2026-04-15,SmartPlug,Kolhapur,4,1817,7268,3.7,Distributor,No,3.45
99,ORD0100,2026-04-13,WaterMeter,Pune,15,1221,18315,3.6,Retail,Yes,36.47

Filling missing Quantity with the column mean (fillna):

,OrderID,OrderDate,Product,City,Quantity,UnitPrice,Revenue,CustomerRating,SalesChannel,Returned,EstimatedCO2SavedKg
0,ORD0001,2026-06-13,EcoBottle,Pune,9,2506,22554,3.4,Distributor,Yes,15.81
1,ORD0002,2026-05-20,EcoBottle,Solapur,2,744,1488,3.2,Online,No,3.17
2,ORD0003,2026-05-24,SolarLamp,Solapur,8,4179,33432,4.2,Online,No,14.45
3,ORD0004,2026-03-29,SmartPlug,Nashik,7,3257,22799,3.2,Retail,Yes,7.18
4,ORD0005,2026-03-30,WaterMeter,Aurangabad,2,4263,8526,4.1,Retail,Yes,2.94
...,...,...,...,...,...,...,...,...,...,...,...
95,ORD0096,2026-01-11,AirSensor,Kolhapur,20,2551,51020,3.1,Online,No,31.01
96,ORD0097,2026-01-06,HealthBand,Aurangabad,19,829,15751,4.5,Online,No,26.48
97,ORD0098,2026-04-24,SmartPlug,Nashik,19,4070,77330,4.3,Retail,Yes,24.34
98,ORD0099,2026-04-15,SmartPlug,Kolhapur,4,1817,7268,3.7,Distributor,No,3.45
99,ORD0100,2026-04-13,WaterMeter,Pune,15,1221,18315,3.6,Retail,Yes,36.47